### ISSUE TITLE
Regarding DHT

### ISSUE THREAD

**Issue by transdeveloper** [DavidIlie/dht#1]
Hello, David.

Instead of doing all in Node,
Why not make a html, with an input.

And a keyboard event, to send a request to your backend, and get a response, as in the url that is assigned.

Also, I like your UI, it's not like dro.pm
But, the fact that there are two inputs makes it confusing.

This issue report is more or a recommendation.

~Nyaa#0288

**Comment by DavidIlie** [comment]
Hey,

I like your suggestions, however, I don't aim to continue development with this project unless I want to try something new. 

I will be closing the issue for now, however if I plan on continuing, I will open the issue and start development :)

Thanks!
